version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7063:7063"
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Ex@mpl3Pass"
      ACCEPT_EULA: "Y"
    ports:
      - "3214:1433"    
    networks:
      - mynetwork 